name: Backend Production (Render Deploy Hook)

on:
  push:
    branches: [ main, master ]

jobs:
  render-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
            echo "RENDER_DEPLOY_HOOK secret not set. Skipping."
            exit 0
          fi
          curl -fsSL -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
